name: 'CIRC Manager Regression Test'

on:
  push:
    branches: [ main ]
  schedule:
    - cron:  '0 0 * * *'

jobs:
  ubuntu-job:
    name: 'Test on Ubuntu'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0.0']
    env: 
        NODE_ENV: test
        SELENIUM_HUB_HOST: hub
        TEST_HOST: testHost
        CIRC_USERNAME: ${{ secrets.CIRC_USERNAME }}
        CIRC_PASSWORD: ${{ secrets.CIRC_PASSWORD }}
    steps:
      # The next 3 steps are for building the web application to be tested and starting the web server on the runner environment
      - name: 'Checkout the repository'
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1 
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Run bundler & gem installs
        run: |
          gem install bundler
          bundle install
      - name: Run RSpec Test
        run: app_type=headless rspec
      - name: Debug via Folder Structure
        run: ls
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: reports/allure-results
          allure_history: allure-history
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
      - name: CIRC Manager Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env: 
          SLACK_CHANNEL: test_reports
          SLACK_MESSAGE: 'https://nypl.github.io/rspec_circ_manager'
          SLACK_TITLE: CIRC Manager Test Results
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: circBot
